export const VALUE_MAP = {
  STRING: 'java.lang.String',
  INTEGER: 'java.lang.Integer',
  BOOLEAN: 'java.lang.Boolean',
  LONG: 'java.lang.Long',
  DOUBLE: 'java.lang.Double',
  SHORT: 'java.lang.Short',
  BYTE: 'java.lang.Byte',
  CHARACTER: 'java.lang.Character',
  FLOAT: 'java.lang.Float',
  MAP: 'java.util.Map',
  LIST: 'java.util.List',
  OBJECT: 'java.lang.Object',
  JSONOBJECT: 'com.alibaba.fastjson.JSONObject',
  VOID: 'VOID',
}
